# 实际开发的时候，database配置务必修改一下

development:
  adapter: mysql2
  encoding: utf8
  database: small-team-km-server-development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: small-team-km-server-test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: small-team-km-server
  username: root
  password: root
  host: localhost